### PR TITLE
Updating README and pulling in the fixes from Nov18

### PR DESCRIPTION
**Pull request by moxiegirl**
Signed-off-by: Mary Anthony <mary@blockstack.com>

### CODE REVIEW

**Comment by moxiegirl** [comment]
@larrysalibra Let me know if you are comfortable with this. I'll merge it now that Aaron has given me the proper perms.

**Review by larrysalibra — CHANGES_REQUESTED** [review]
The copy change look great. However the two links circled in the screenshot have issues.

1st is broken 

Second leads to something about the android sdk 

31882595-632e-4af3-ab46-7b7115ad1cce

**Comment by larrysalibra** [comment]
CircleCI tests are failing cc @shreyasthiagaraj

**Review by moxiegirl — COMMENTED** [review]
Should be fixed now @larrysalibra

**Review by larrysalibra — APPROVED** [review]
Looks great to me! Thank you @moxiegirl !

**Comment by moxiegirl** [comment]
Thanks @larrysalibra .  @yknl I don't want to merge this with a Circle CI issue, who is the new maintainer here now that @shreyasthiagaraj is off to further adventures?

  🍻

**Comment by shreyasthiagaraj** [comment]
@moxiegirl It's still me. I'll be back next week, can this wait until then?

**Comment by moxiegirl** [comment]
@larrysalibra filed the issue, so I think he should say. It *is* the README but it has been about 4 months and only two people called it out.  The docs are fixed.

**Comment by larrysalibra** [comment]
@shreyasthiagaraj I think it's fine to merge these readme changes since the typos look pretty bad.

I've opened a separate issue about the circleci tests: https://github.com/blockstack/blockstack-ios/issues/73

**Pull request merged**
