### PR TITLE
Update the structure and the tutorial even with Android

### PR DESCRIPTION
**Pull request by moxiegirl**
@shreyasthiagaraj Here is the replacement for the previous PR.

### CODE REVIEW

**Review by shreyasthiagaraj — APPROVED** [review]
Awesome. This looks good to me, thank you for making such a detailed tutorial and for implementing my feedback. I wish I had this tutorial when I got started!

**Comment by moxiegirl** [comment]
@shreyasthiagaraj  I don't have perms to merge this.  If you like the result, please go ahead and merge it.

**Comment by shreyasthiagaraj** [comment]
@moxiegirl I've merged this into `develop`. It will go into `master` with our next release of the SDK (v0.4.0).

**Comment by moxiegirl** [comment]
🎉 Woot! Thanks @shreyasthiagaraj

**Pull request merged**
